import { NextPage, InferGetStaticPropsType } from "next";
import { useRouter } from "next/router";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import "prismjs/themes/prism-tomorrow.css";
import "prismjs/plugins/line-numbers/prism-line-numbers.css";
import fs from "fs";
import path from "path";
import { getDocsFileName } from "./api/fetch";

type Props = InferGetStaticPropsType<typeof getStaticProps>;

const examplesDirectory = path.join(process.cwd(), "../examples");

export const getStaticProps = async ({ params }: any) => {

  return {
    props: {
      examples: getDocsFileName("../example", ".html"),
    },
  };
};

const Doc: NextPage<Props> = ({ examples }) => {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Hello world!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Examples</h1>
        <ul>
          {examples.map((name, i) => (
            <li key={`${i}`}>
              <a href={`example/${name}`}>{name}</a>
            </li>
          ))}
        </ul>
      </main>
    </div>
  );
};

export default Doc;
