import * as ex from "../compile-tests/ex_nested_gen";
import * as samples_tmp from "../compile-tests/ex_nested_examples.json";
import * as schema_tmp from "../compile-tests/ex_nested_schema.json";
import * as schema_variant from "../compile-tests/ex_variant_schema.json";
import { Schema } from "jsonschema";
import { validationTest } from "./helper";

const allSchema: Schema[] = <Schema[]>(<unknown>schema_tmp);
const refs: Schema[] = <Schema[]>(<unknown>schema_variant);

describe("ex_nested", (): void => {
  describe("ExNestedPoint2", () => {
    // also typecheck the generate JSON
    const samples: ex.ExNestedPoint2[] = <ex.ExNestedPoint2[]>samples_tmp.ExNestedPoint2;

    test("it compiles", (): void => {
      expect(samples[0].x).toBe(1);
      expect(samples[0].y).toBe(2);
    });

    test("schema validates all the examples", validationTest(allSchema, samples, "#ExNestedPoint2"));
  });

  describe("ExNestedRecord", () => {
    // also typecheck the generate JSON
    const samples: ex.ExNestedRecord[] = <ex.ExNestedRecord[]>samples_tmp.ExNestedRecord;

    test("it compiles", (): void => {
      expect(samples).toStrictEqual([
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "tuple-like" },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "tuple-like", arg: 42 },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "tuple-like-alias" },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "tuple-like-alias", arg: 42 },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "tuple-like-obj" },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "tuple-like-obj", _0: 42 },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "tuple-like-obj", _1: 128 },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "tuple-like-obj", _0: 256, _1: 23 },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "tuple-like-spreading" },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "tuple-like-spreading", yOpt: 42 },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "tuple-like-spreading", xOpt: -25 },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "tuple-like-spreading", xOpt: 512, yOpt: -119 },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", objtuple: {} },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", objtuple: { _0: 42 } },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", objtuple: { _1: 128 } },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", objtuple: { _0: 256, _1: 23 } },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", yOpt: 42, objtuple: {} },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", yOpt: 42, objtuple: { _0: 42 } },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", yOpt: 42, objtuple: { _1: 128 } },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", yOpt: 42, objtuple: { _0: 256, _1: 23 } },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", xOpt: -25, objtuple: {} },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", xOpt: -25, objtuple: { _0: 42 } },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", xOpt: -25, objtuple: { _1: 128 } },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", xOpt: -25, objtuple: { _0: 256, _1: 23 } },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", xOpt: 512, yOpt: -119, objtuple: {} },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", xOpt: 512, yOpt: -119, objtuple: { _0: 42 } },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", xOpt: 512, yOpt: -119, objtuple: { _1: 128 } },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", xOpt: 512, yOpt: -119, objtuple: { _0: 256, _1: 23 } },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", intOpt: 42, objtuple: {} },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", intOpt: 42, objtuple: { _0: 42 } },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", intOpt: 42, objtuple: { _1: 128 } },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", intOpt: 42, objtuple: { _0: 256, _1: 23 } },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", intOpt: 42, yOpt: 42, objtuple: {} },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", intOpt: 42, yOpt: 42, objtuple: { _0: 42 } },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", intOpt: 42, yOpt: 42, objtuple: { _1: 128 } },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", intOpt: 42, yOpt: 42, objtuple: { _0: 256, _1: 23 } },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", intOpt: 42, xOpt: -25, objtuple: {} },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", intOpt: 42, xOpt: -25, objtuple: { _0: 42 } },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", intOpt: 42, xOpt: -25, objtuple: { _1: 128 } },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", intOpt: 42, xOpt: -25, objtuple: { _0: 256, _1: 23 } },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", intOpt: 42, xOpt: 512, yOpt: -119, objtuple: {} },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", intOpt: 42, xOpt: 512, yOpt: -119, objtuple: { _0: 42 } },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record", intOpt: 42, xOpt: 512, yOpt: -119, objtuple: { _1: 128 } },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: {
            tag: "inline-record",
            intOpt: 42,
            xOpt: 512,
            yOpt: -119,
            objtuple: { _0: 256, _1: 23 },
          },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record-spreading" },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record-spreading", yOpt: 42 },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record-spreading", xOpt: -25 },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record-spreading", xOpt: 512, yOpt: -119 },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record-spreading", intOpt: 42 },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record-spreading", intOpt: 42, yOpt: 42 },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record-spreading", intOpt: 42, xOpt: -25 },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "inline-record-spreading", intOpt: 42, xOpt: 512, yOpt: -119 },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "reused-inline-record" },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "reused-inline-record", yOpt: 42 },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "reused-inline-record", xOpt: -25 },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Anonymous" },
          optionalVariant: { tag: "reused-inline-record", xOpt: 512, yOpt: -119 },
          kind: "Anonymous",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "tuple-like" },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "tuple-like", arg: 42 },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "tuple-like-alias" },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "tuple-like-alias", arg: 42 },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "tuple-like-obj" },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "tuple-like-obj", _0: 42 },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "tuple-like-obj", _1: 128 },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "tuple-like-obj", _0: 256, _1: 23 },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "tuple-like-spreading" },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "tuple-like-spreading", yOpt: 42 },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "tuple-like-spreading", xOpt: -25 },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "tuple-like-spreading", xOpt: 512, yOpt: -119 },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", objtuple: {} },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", objtuple: { _0: 42 } },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", objtuple: { _1: 128 } },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", objtuple: { _0: 256, _1: 23 } },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", yOpt: 42, objtuple: {} },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", yOpt: 42, objtuple: { _0: 42 } },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", yOpt: 42, objtuple: { _1: 128 } },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", yOpt: 42, objtuple: { _0: 256, _1: 23 } },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", xOpt: -25, objtuple: {} },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", xOpt: -25, objtuple: { _0: 42 } },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", xOpt: -25, objtuple: { _1: 128 } },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", xOpt: -25, objtuple: { _0: 256, _1: 23 } },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", xOpt: 512, yOpt: -119, objtuple: {} },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", xOpt: 512, yOpt: -119, objtuple: { _0: 42 } },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", xOpt: 512, yOpt: -119, objtuple: { _1: 128 } },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", xOpt: 512, yOpt: -119, objtuple: { _0: 256, _1: 23 } },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", intOpt: 42, objtuple: {} },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", intOpt: 42, objtuple: { _0: 42 } },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", intOpt: 42, objtuple: { _1: 128 } },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", intOpt: 42, objtuple: { _0: 256, _1: 23 } },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", intOpt: 42, yOpt: 42, objtuple: {} },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", intOpt: 42, yOpt: 42, objtuple: { _0: 42 } },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", intOpt: 42, yOpt: 42, objtuple: { _1: 128 } },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", intOpt: 42, yOpt: 42, objtuple: { _0: 256, _1: 23 } },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", intOpt: 42, xOpt: -25, objtuple: {} },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", intOpt: 42, xOpt: -25, objtuple: { _0: 42 } },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", intOpt: 42, xOpt: -25, objtuple: { _1: 128 } },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", intOpt: 42, xOpt: -25, objtuple: { _0: 256, _1: 23 } },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", intOpt: 42, xOpt: 512, yOpt: -119, objtuple: {} },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", intOpt: 42, xOpt: 512, yOpt: -119, objtuple: { _0: 42 } },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record", intOpt: 42, xOpt: 512, yOpt: -119, objtuple: { _1: 128 } },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: {
            tag: "inline-record",
            intOpt: 42,
            xOpt: 512,
            yOpt: -119,
            objtuple: { _0: 256, _1: 23 },
          },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record-spreading" },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record-spreading", yOpt: 42 },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record-spreading", xOpt: -25 },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record-spreading", xOpt: 512, yOpt: -119 },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record-spreading", intOpt: 42 },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record-spreading", intOpt: 42, yOpt: 42 },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record-spreading", intOpt: 42, xOpt: -25 },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "inline-record-spreading", intOpt: 42, xOpt: 512, yOpt: -119 },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "reused-inline-record" },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "reused-inline-record", yOpt: 42 },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "reused-inline-record", xOpt: -25 },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "With_id", value: 1619 },
          optionalVariant: { tag: "reused-inline-record", xOpt: 512, yOpt: -119 },
          kind: "With_id",
          value: 1619,
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "tuple-like" },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "tuple-like", arg: 42 },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "tuple-like-alias" },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "tuple-like-alias", arg: 42 },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "tuple-like-obj" },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "tuple-like-obj", _0: 42 },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "tuple-like-obj", _1: 128 },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "tuple-like-obj", _0: 256, _1: 23 },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "tuple-like-spreading" },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "tuple-like-spreading", yOpt: 42 },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "tuple-like-spreading", xOpt: -25 },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "tuple-like-spreading", xOpt: 512, yOpt: -119 },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", objtuple: {} },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", objtuple: { _0: 42 } },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", objtuple: { _1: 128 } },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", objtuple: { _0: 256, _1: 23 } },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", yOpt: 42, objtuple: {} },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", yOpt: 42, objtuple: { _0: 42 } },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", yOpt: 42, objtuple: { _1: 128 } },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", yOpt: 42, objtuple: { _0: 256, _1: 23 } },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", xOpt: -25, objtuple: {} },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", xOpt: -25, objtuple: { _0: 42 } },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", xOpt: -25, objtuple: { _1: 128 } },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", xOpt: -25, objtuple: { _0: 256, _1: 23 } },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", xOpt: 512, yOpt: -119, objtuple: {} },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", xOpt: 512, yOpt: -119, objtuple: { _0: 42 } },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", xOpt: 512, yOpt: -119, objtuple: { _1: 128 } },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", xOpt: 512, yOpt: -119, objtuple: { _0: 256, _1: 23 } },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", intOpt: 42, objtuple: {} },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", intOpt: 42, objtuple: { _0: 42 } },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", intOpt: 42, objtuple: { _1: 128 } },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", intOpt: 42, objtuple: { _0: 256, _1: 23 } },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", intOpt: 42, yOpt: 42, objtuple: {} },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", intOpt: 42, yOpt: 42, objtuple: { _0: 42 } },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", intOpt: 42, yOpt: 42, objtuple: { _1: 128 } },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", intOpt: 42, yOpt: 42, objtuple: { _0: 256, _1: 23 } },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", intOpt: 42, xOpt: -25, objtuple: {} },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", intOpt: 42, xOpt: -25, objtuple: { _0: 42 } },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", intOpt: 42, xOpt: -25, objtuple: { _1: 128 } },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", intOpt: 42, xOpt: -25, objtuple: { _0: 256, _1: 23 } },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", intOpt: 42, xOpt: 512, yOpt: -119, objtuple: {} },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", intOpt: 42, xOpt: 512, yOpt: -119, objtuple: { _0: 42 } },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record", intOpt: 42, xOpt: 512, yOpt: -119, objtuple: { _1: 128 } },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: {
            tag: "inline-record",
            intOpt: 42,
            xOpt: 512,
            yOpt: -119,
            objtuple: { _0: 256, _1: 23 },
          },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record-spreading" },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record-spreading", yOpt: 42 },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record-spreading", xOpt: -25 },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record-spreading", xOpt: 512, yOpt: -119 },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record-spreading", intOpt: 42 },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record-spreading", intOpt: 42, yOpt: 42 },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record-spreading", intOpt: 42, xOpt: -25 },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "inline-record-spreading", intOpt: 42, xOpt: 512, yOpt: -119 },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "reused-inline-record" },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "reused-inline-record", yOpt: 42 },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "reused-inline-record", xOpt: -25 },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "student", student_id: 451, name: "Ray Bradbury", caseValue: "Case_at0" },
          optionalVariant: { tag: "reused-inline-record", xOpt: 512, yOpt: -119 },
          kind: "student",
          student_id: 451,
          name: "Ray Bradbury",
          caseValue: "Case_at0",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "tuple-like" },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "tuple-like", arg: 42 },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "tuple-like-alias" },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "tuple-like-alias", arg: 42 },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "tuple-like-obj" },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "tuple-like-obj", _0: 42 },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "tuple-like-obj", _1: 128 },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "tuple-like-obj", _0: 256, _1: 23 },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "tuple-like-spreading" },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "tuple-like-spreading", yOpt: 42 },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "tuple-like-spreading", xOpt: -25 },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "tuple-like-spreading", xOpt: 512, yOpt: -119 },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", objtuple: {} },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", objtuple: { _0: 42 } },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", objtuple: { _1: 128 } },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", objtuple: { _0: 256, _1: 23 } },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", yOpt: 42, objtuple: {} },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", yOpt: 42, objtuple: { _0: 42 } },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", yOpt: 42, objtuple: { _1: 128 } },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", yOpt: 42, objtuple: { _0: 256, _1: 23 } },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", xOpt: -25, objtuple: {} },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", xOpt: -25, objtuple: { _0: 42 } },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", xOpt: -25, objtuple: { _1: 128 } },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", xOpt: -25, objtuple: { _0: 256, _1: 23 } },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", xOpt: 512, yOpt: -119, objtuple: {} },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", xOpt: 512, yOpt: -119, objtuple: { _0: 42 } },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", xOpt: 512, yOpt: -119, objtuple: { _1: 128 } },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", xOpt: 512, yOpt: -119, objtuple: { _0: 256, _1: 23 } },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", intOpt: 42, objtuple: {} },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", intOpt: 42, objtuple: { _0: 42 } },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", intOpt: 42, objtuple: { _1: 128 } },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", intOpt: 42, objtuple: { _0: 256, _1: 23 } },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", intOpt: 42, yOpt: 42, objtuple: {} },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", intOpt: 42, yOpt: 42, objtuple: { _0: 42 } },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", intOpt: 42, yOpt: 42, objtuple: { _1: 128 } },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", intOpt: 42, yOpt: 42, objtuple: { _0: 256, _1: 23 } },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", intOpt: 42, xOpt: -25, objtuple: {} },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", intOpt: 42, xOpt: -25, objtuple: { _0: 42 } },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", intOpt: 42, xOpt: -25, objtuple: { _1: 128 } },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", intOpt: 42, xOpt: -25, objtuple: { _0: 256, _1: 23 } },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", intOpt: 42, xOpt: 512, yOpt: -119, objtuple: {} },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", intOpt: 42, xOpt: 512, yOpt: -119, objtuple: { _0: 42 } },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record", intOpt: 42, xOpt: 512, yOpt: -119, objtuple: { _1: 128 } },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: {
            tag: "inline-record",
            intOpt: 42,
            xOpt: 512,
            yOpt: -119,
            objtuple: { _0: 256, _1: 23 },
          },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record-spreading" },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record-spreading", yOpt: 42 },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record-spreading", xOpt: -25 },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record-spreading", xOpt: 512, yOpt: -119 },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record-spreading", intOpt: 42 },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record-spreading", intOpt: 42, yOpt: 42 },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record-spreading", intOpt: 42, xOpt: -25 },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "inline-record-spreading", intOpt: 42, xOpt: 512, yOpt: -119 },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "reused-inline-record" },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "reused-inline-record", yOpt: 42 },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "reused-inline-record", xOpt: -25 },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
        {
          unit: 1,
          point2: { x: 1, y: 2 },
          x: 1,
          y: 2,
          person: { kind: "Teacher", facultyId: 2001, name: "Arthur C. Clark", department: "Space" },
          optionalVariant: { tag: "reused-inline-record", xOpt: 512, yOpt: -119 },
          kind: "Teacher",
          facultyId: 2001,
          name: "Arthur C. Clark",
          department: "Space",
        },
      ]);
    });

    test("schema validates all the examples", validationTest(allSchema, samples, "#ExNestedRecord"));
  });

  describe("ExNestedVariant", () => {
    // also typecheck the generate JSON
    const samples: ex.ExNestedVariant[] = <ex.ExNestedVariant[]>samples_tmp.ExNestedVariant;

    test("it compiles", () => {
      expect(samples).toStrictEqual([
        { tag: "student1", student: { admissionYear: 1984, name: "William Gibson" } },
        { tag: "student2", admissionYear: 1984, name: "William Gibson" },
        { tag: "student3", arg: { admissionYear: 1984, name: "William Gibson" } },
        { tag: "student4", admissionYear: 1984, name: "William Gibson" },
        { tag: "int-list1", arg: { kind: "intcons", value: [1, { kind: "intcons", value: [2, { kind: "intnil" }] }] } },
        { tag: "int-list2", kind: "intcons", value: [1, { kind: "intcons", value: [2, { kind: "intnil" }] }] },
      ]);
    });

    test("schema validates all the examples", validationTest(allSchema, samples, "#ExNestedVariant", refs));
  });
});
