name: Common CI workflow

on:
  workflow_dispatch:
  pull_request:
    types: [closed]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.12.1
          - 4.13.x
          - 4.14.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}

      - name: Cache OPAM switch
        id: cache-switch
        uses: actions/cache@v3
        with:
          path: _opam
          key: v1-${{ runner.os }}-${{ matrix.ocaml-version }}-opam-switch

      - name: check OCaml version and workspace info
        run: |
          echo ">>> uname -a"
          uname -a
          echo && echo ">>> OCaml --version"
          opam exec -- ocamlc --version
          echo && echo ">>> git status"
          git show HEAD^..HEAD --stat || git show HEAD --stat
          echo && echo ">>> git ls-files"
          git ls-files

      - run: opam install . --deps-only --with-test
      - run: opam exec -- dune build
      - run: opam exec -- dune runtest
