name: Matrix Check

on:
  pull_request_review:
    types: [submitted]

jobs:
  matrix-check:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.13.x
          - 4.14.x
        node-version:
          - lts/fermium # v14 Maintenance LTS
          - lts/gallium # v16 Active LTS
          - 17

    if: |
      github.event.review.state == 'approved' &&
      github.repository == 'kxcinc/bindoj'
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: 'with_js/yarn.lock'

      - name: Cache OPAM switch
        id: cache-switch
        uses: actions/cache@v3
        with:
          path: _opam
          key: v1-${{ runner.os }}-${{ matrix.ocaml-version }}-opam-switch

      - name: check OCaml version and workspace info
        run: ./scripts/ci_print_env.sh

      - name: Install dependencies
        run: opam install . --deps-only --with-test

      - name: build & test
        run: ./scripts/ci_run.sh
