name: Audit

on:
  push:

jobs:
  audit:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - lts/hydrogen # v18 Active LTS

    if: github.repository == 'kxcinc/bindoj'
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: 'with_js/yarn.lock'

      - name: Audit code
        run: make audit
