name: Mirror to kxcdev/bindoj

on:
  push:
    branches:
      - 'main'

jobs:
  mirror:
    if: github.repository == 'kxcinc/bindoj'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to kxcdev/bindoj
        env:
          BRANCH: ${{ github.ref_name }}
          SSH_KEY: ${{ secrets.SSH_KEY_KXCDEV_BINDOJ_DEPLOYMENT }}
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< "${SSH_KEY}"
          git push -f git@github.com:kxcdev/bindoj.git --set-upstream "$BRANCH"
