name: ocaml-general CI workflow

on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ocaml-version:
          - 4.14.2
          - 5.1.1
          - 5.3.0

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kxcinc/ocaml-general:${{ matrix.ocaml-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 2

      # https://github.blog/2022-04-12-git-security-vulnerability-announced/
      - name: Safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: check OCaml version and workspace info
        run: ./scripts/ci_print_env.sh

      - run: ./scripts/ci_setup_ubuntu.sh

      - run: opam update

      - name: Install dependencies
        run: opam install . --yes --deps-only --with-test --verbose

      - name: build & test
        run: ./scripts/ci_run.sh

  ocaml-general-checked:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "all set"
